repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: flake8
        config_file: .flake8
-   repo: local
    hooks:
    -   id: run-tests
        language: script
        name: Run tests
        entry: ./run_tests.sh
        stages: [commit]
