[tool.ruff]
exclude = [
    "*/venv/*",
    "*/migrations/*",
    "apps.py",
    "*/settings/*",
    ]
ignore = ["E402", "E501", "F403"]

[tool.black]
exclude = ["*/migrations/*"]


# F403 is ignored because I use * imports in settings files
# E402 is ignored because If I change the order of imports, I get an error when running tests
# E501 is ignored because sometimes I have long lines that I don't want to split
